### ISSUE TITLE
 get a NullPointerException

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine-Contributions/zay-es#14]
Hi
I want to make a patch for this issue https://hub.jmonkeyengine.org/t/understanding-stringindex-interface-in-package-com-simsilica-es/37143/5?u=ali_rs
If `getStringId("some string", false)` can not find id for "some string" it will return null Integer result.
Now, the result has to be unboxed again to int, because the return type of the method is int. If you unbox an Integer that is null, you get a NullPointerException.

There is two way to fix it: 
1- Change return type to Integer instead of int 
2- or return -1 if result is null
Which one do you prefer ?

**Comment by pspeed42** [comment]
Return -1... else everyone would have to clean build because of the method signature change.

**Comment by pspeed42** [comment]
And usually, I'd probably use an inline conditional in this case.

**Comment by Ali-RS** [comment]
> else everyone would have to clean build because of the method signature change.

Yes, I agree. Interface should not change.

**Comment by pspeed42** [comment]
I've committed a fix.  If you get a chance to test it in your case then can you close the issue?

**Comment by Ali-RS** [comment]
It's OK.
