### ISSUE TITLE
Supporting primitive array field type for sql components

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine-Contributions/zay-es#16]
Hi 
Array type is supported in standard sql as well in hsqldb. See http://hsqldb.org/web/howToArrays.html. 
In the above link it describes an example of using array is to store Polygons which is exactly my usecase. 

I am using a dynamic polygonal path finding library, there we need to create obstacles out of polygons or polylines and add the to navigation space. 
I need to save polygon vertices for obstacle in a float [] field in `Obstacle` component. 
Please take a look at the readme for this project  https://github.com/implicit-invocation/jwalkable. 

Regards

**Comment by Ali-RS** [comment]
For the moment I continue with saving the array as an string with "," separated. 
I think adding a patch to support sql Array will be easy . 
I will take a look at it later.

**Comment by pspeed42** [comment]
I'm interested in supporting this.  I don't know when I will get a chance to add it but if someone submits a PR then I will take a close look at it.
