### ISSUE TITLE
Update javadoc for getStringId()

### ISSUE THREAD

**Issue by mitm001** [jMonkeyEngine-Contributions/zay-es#20]
https://hub.jmonkeyengine.org/t/understanding-stringindex-interface-in-package-com-simsilica-es/37143

**Comment by pspeed42** [comment]
Just leaving this note here for my own reference.  Probably the most salient comment in that thread is:

> Often times you want what are effectively strings but where the actual number of different string values might be limited. For example, object type names. There will probably only be a handful of them but the flexibility in code of referring to them by string is nice… rather than having to defined a bunch of constant ints somewhere and keep them all in sync.
>
> Because the number of strings is finite, sending full strings over the wire and/or storing them in a database is wasteful. String index lets you convert them to/from unique integer IDs that are safely stored in the ES.
>
> getStringId(“my string”, true)
> …will return an integer ID for the string “my string” or create one if it doesn’t already have one. If you pass false then it will return -1 if the string doesn’t already exist.
> 
> getString(id)
> …is the reverse of that for if you want to in-code see what the value is again (usually for debug or user interface output).
> 
> I should probably fill out the javadoc for those methods and add a section to the nascent zay-es wiki.

**Comment by pspeed42** [comment]
Added javadoc in this commit: https://github.com/jMonkeyEngine-Contributions/zay-es/commit/42f109b9d1e58b42d2de7dba6685193cbe973a48

Let me know if it's still unclear in some way... can reopen this issue if so.
