### ISSUE TITLE
 Issue with entity removal

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine-Contributions/zay-es#27]
When I remove an entity from EntityData using `removeEntity()` method, it publishes an EntityChange event for ALL the component types even if that entity does not have the component at all. It is because the `removeComponent()` method does not check the result from handler to see if the remove operation is valid or not before it publishes the event in this line:

https://github.com/jMonkeyEngine-Contributions/zay-es/blob/78d320dbdb9d9aa9598752ce839b9618a4e571c7/src/main/java/com/simsilica/es/base/DefaultEntityData.java#L202-L205

**Comment by Ali-RS** [comment]
Fixed in https://github.com/jMonkeyEngine-Contributions/zay-es/commit/b8c4c050bcaf5b1794de1aae6e2b68ea3e9f1e46

Thanks, @pspeed42

**Comment by pspeed42** [comment]
Thanks for closing the loop for me here.
